# Generated by Django 3.1.7 on 2021-04-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=122)),
                ('upload_file', models.FileField(upload_to='statics/files')),
            ],
        ),
    ]
