# Generated by Django 3.1.7 on 2021-04-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload_file',
            field=models.FileField(upload_to=''),
        ),
    ]
