# Generated by Django 3.1.7 on 2021-04-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210408_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload_file',
            field=models.FileField(upload_to='files'),
        ),
    ]
