# Generated by Django 3.1.7 on 2021-04-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210408_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=122)),
                ('election_date', models.DateField()),
                ('filename', models.CharField(max_length=122)),
                ('election_img', models.ImageField(upload_to='electionimg')),
                ('upload_file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
