# Generated by Django 3.1.7 on 2021-04-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_votegivendata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=122)),
                ('party_name', models.CharField(max_length=122)),
            ],
        ),
    ]
